### PR TITLE
Update CentOS yum task to remove deprecation warning

### PR DESCRIPTION
**Pull request by britthouser**
Running yum in a loop using with_items is deprecated and ansible
issues a warning that this will be removed in 2.11.  Instead
multiple packages should be listed under name.

### CODE REVIEW

**Comment by britthouser** [comment]
@aprt5pr  - I've included a second commit which fixes the CentOS gate. I'm not sure why the ubuntu gate is failing, but doesn't seem to be related to this patch.  Thoughts?

**Comment by aprt5pr** [comment]
@britthouser the yum changes seem fine. Does that syntax work with all Ansible versions >= 2.0? If not, we should also update the galaxy metadata with a new min version.

It makes sense to stat the certs before testing the config. It's not clear to me though why we would still restart the service when stat'ing the certs has [failed](https://github.com/aprt5pr/lansible-role-ocserv/pull/5/commits/c3761e3c4a5461fa063dde983ca6503b2246b986#diff-2444ad0870f91f17ca6c2a5e96b26823R106). Maybe I'm missing something there.

**Comment by britthouser** [comment]
@aprt5pr  - According to https://docs.ansible.com/ansible/latest/modules/yum_module.html, this new syntax was available with 2.0.  So I don't think we'll have to update the metadata.

If the cert stat fails, then ocserv will create self-signed certs when it starts.  So its still OK to start the service without any cert files.  However, the config check will fail if the cert files don't exist.  So the change here is to only perform the config check if the cert files exist.  Does that make sense?

**Comment by britthouser** [comment]
@aprt5pr - Any other changes you'd like to see with this commit, or are we good to go?

**Comment by aprt5pr** [comment]
@britthouser merged

**Comment by britthouser** [comment]
Thanks @aprt5pr

**Pull request merged**
